import type { ColombiaData } from './types';

export const colombiaData: ColombiaData = {
  "Amazonas": ["Leticia", "Puerto Nariño", "El Encanto", "La Chorrera", "La Pedrera", "Mirití-Paraná", "Puerto Alegría", "Puerto Arica", "Puerto Santander", "Tarapacá"],
  "Antioquia": ["Medellín", "Bello", "Envigado", "Itagüí", "Sabaneta", "Rionegro", "Apartadó", "Caldas", "Caucasia", "Copacabana", "Girardota", "La Ceja", "La Estrella", "Marinilla", "Turbo"],
  "Arauca": ["Arauca", "Saravena", "Tame", "Arauquita", "Cravo Norte", "Fortul", "Puerto Rondón"],
  "Atlántico": ["Barranquilla", "Soledad", "Malambo", "Galapa", "Baranoa", "Campo de la Cruz", "Candelaria", "Juan de Acosta", "Luruaco", "Manatí", "Palmar de Varela", "Piojó", "Polonuevo", "Ponedera", "Puerto Colombia", "Repelón", "Sabanagrande", "Sabanalarga", "Santa Lucía", "Santo Tomás", "Suán", "Usiacurí"],
  "Bolívar": ["Cartagena", "Magangué", "Turbaco", "Arjona", "Carmen de Bolívar", "Mompox", "Santa Rosa del Sur", "Simití", "Tiquisio", "El Peñón"],
  "Boyacá": ["Tunja", "Duitama", "Sogamoso", "Villa de Leyva", "Chiquinquirá", "Paipa", "Puerto Boyacá", "Garagoa", "Moniquirá", "Samacá"],
  "Caldas": ["Manizales", "La Dorada", "Chinchiná", "Riosucio", "Villamaría", "Neira", "Salamina", "Supía", "Anserma", "Aguadas"],
  "Caquetá": ["Florencia", "San Vicente del Caguán", "Belén de los Andaquíes", "Cartagena del Chairá", "Curillo", "El Doncello", "El Paujil", "La Montañita", "Milán", "Morelia", "Puerto Rico", "Solano", "Solita", "Valparaíso"],
  "Casanare": ["Yopal", "Aguazul", "Villanueva", "Paz de Ariporo", "Tauramena", "Trinidad", "Maní", "Monterrey", "Sabanalarga", "San Luis de Palenque"],
  "Cauca": ["Popayán", "Santander de Quilichao", "Puerto Tejada", "Piendamó", "El Bordo", "Miranda", "Cajibío", "Timbío", "Villa Rica", "Corinto"],
  "Cesar": ["Valledupar", "Aguachica", "Agustín Codazzi", "Bosconia", "Chimichagua", "Curumaní", "El Copey", "La Jagua de Ibirico", "Pailitas", "San Alberto"],
  "Chocó": ["Quibdó", "Istmina", "Tadó", "Condoto", "El Carmen de Atrato", "Riosucio", "Bahía Solano", "Nuquí", "Acandí", "Juradó"],
  "Córdoba": ["Montería", "Cereté", "Sahagún", "Lorica", "Planeta Rica", "Montelíbano", "Tierralta", "San Andrés de Sotavento", "Chinú", "Ciénaga de Oro"],
  "Cundinamarca": ["Bogotá", "Soacha", "Zipaquirá", "Chía", "Girardot", "Fusagasugá", "Facatativá", "Mosquera", "Madrid", "Funza", "Ubaté", "Sibaté", "Cajicá", "Villeta"],
  "Guainía": ["Inírida", "Barrancominas", "Cacahual", "La Guadalupe", "Mapiripana", "Morichal Nuevo", "Pana Pana", "Puerto Colombia", "San Felipe"],
  "Guaviare": ["San José del Guaviare", "Calamar", "El Retorno", "Miraflores"],
  "Huila": ["Neiva", "Pitalito", "Garzón", "La Plata", "Campoalegre", "Gigante", "Rivera", "Aipe", "Palermo", "Yaguará"],
  "La Guajira": ["Riohacha", "Maicao", "Uribia", "Fonseca", "San Juan del Cesar", "Barrancas", "Dibulla", "Hatonuevo", "Albania", "Villanueva"],
  "Magdalena": ["Santa Marta", "Ciénaga", "Fundación", "El Banco", "Plato", "Aracataca", "Pivijay", "Salamina", "San Zenón", "Santa Ana"],
  "Meta": ["Villavicencio", "Acacías", "Granada", "Puerto López", "Puerto Gaitán", "San Martín", "Cumaral", "Restrepo", "Castilla la Nueva", "Guamal"],
  "Nariño": ["Pasto", "Ipiales", "Tumaco", "Túquerres", "La Unión", "Samaniego", "Sandona", "Taminango", "El Tambo", "Pupiales"],
  "Norte de Santander": ["Cúcuta", "Ocaña", "Pamplona", "Villa del Rosario", "Los Patios", "Tibú", "El Zulia", "Sardinata", "Ábrego", "Chinácota"],
  "Putumayo": ["Mocoa", "Puerto Asís", "Orito", "Valle del Guamuez", "Sibundoy", "San Miguel", "Puerto Caicedo", "Colón", "San Francisco", "Santiago"],
  "Quindío": ["Armenia", "Calarcá", "Salento", "Montenegro", "Quimbaya", "Circasia", "La Tebaida", "Filandia", "Génova", "Pijao"],
  "Risaralda": ["Pereira", "Dosquebradas", "Santa Rosa de Cabal", "La Virginia", "Marsella", "Belén de Umbría", "Santuario", "Apía", "Quinchía", "Mistrató"],
  "San Andrés y Providencia": ["San Andrés", "Providencia y Santa Catalina"],
  "Santander": ["Bucaramanga", "Floridablanca", "Girón", "Piedecuesta", "Barrancabermeja", "San Gil", "Socorro", "Málaga", "Vélez", "Barbosa"],
  "Sucre": ["Sincelejo", "Corozal", "Tolú", "Coveñas", "Sampués", "San Marcos", "Majagual", "San Onofre", "Ovejas", "Sincé"],
  "Tolima": ["Ibagué", "Espinal", "Melgar", "Honda", "Líbano", "Chaparral", "Mariquita", "Guamo", "Fresno", "Prado"],
  "Valle del Cauca": ["Cali", "Buenaventura", "Palmira", "Tuluá", "Buga", "Cartago", "Jamundí", "Yumbo", "Candelaria", "Roldanillo"],
  "Vaupés": ["Mitú", "Carurú", "Pacoa", "Taraira", "Papunahua", "Yavaraté"],
  "Vichada": ["Puerto Carreño", "La Primavera", "Cumaribo", "Santa Rosalía"]
};
